blueprint:
  name: IKEA SOMRIG actions
  description: Assign any action to the button events
  source_url: https://github.com/lucalouwris/automations/blob/main/IkeaSomrigActions.yaml
  domain: automation
  input:
    device:
      name: Ikea switch
      description: Select the MQTT device that represents the switch.
      selector:
        device:
    action_1_initial_press:
      name: (Optional) 1 initial press
      default: []
      selector:
        action:
    action_1_short_release:
      name: (Optional) 1 short release
      default: []
      selector:
        action:
    action_1_long_press:
      name: (Optional) 1 long press
      default: []
      selector:
        action:
    action_1_long_release:
      name: (Optional) 1 long release
      default: []
      selector:
        action:
    action_1_double_press:
      name: (Optional) 1 double press
      default: []
      selector:
        action:
    action_2_initial_press:
      name: (Optional) 2 initial press
      default: []
      selector:
        action:
    action_2_short_release:
      name: (Optional) 2 short release
      default: []
      selector:
        action:
    action_2_long_press:
      name: (Optional) 2 long press
      default: []
      selector:
        action:
    action_2_long_release:
      name: (Optional) 2 long release
      default: []
      selector:
        action:
    action_2_double_press:
      name: (Optional) 2 double press
      default: []
      selector:
        action:

mode: restart
max_exceeded: silent
alias: Hue Button Actions

trigger:  
  - platform: device
    domain: mqtt
    device_id: !input device
    type: action
    subtype: 1_initial_press
  - platform: device
    domain: mqtt
    device_id: !input device
    type: action
    subtype: 1_short_release
  - platform: device
    domain: mqtt
    device_id: !input device
    type: action
    subtype: 1_long_press
  - platform: device
    domain: mqtt
    device_id: !input device
    type: action
    subtype: 1_long_release
  - platform: device
    domain: mqtt
    device_id: !input device
    type: action
    subtype: 1_double_press
  - platform: device
    domain: mqtt
    device_id: !input device
    type: action
    subtype: 2_initial_press
  - platform: device
    domain: mqtt
    device_id: !input device
    type: action
    subtype: 2_short_release
  - platform: device
    domain: mqtt
    device_id: !input device
    type: action
    subtype: 2_long_press
  - platform: device
    domain: mqtt
    device_id: !input device
    type: action
    subtype: 2_long_release
  - platform: device
    domain: mqtt
    device_id: !input device
    type: action
    subtype: 2_double_press

condition: []

action:
  - variables:
      action: "{{ trigger.payload }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ action == '1_initial_press' }}"
        sequence: !input action_1_initial_press
      - conditions:
          - condition: template
            value_template: "{{ action == '1_short_release' }}"
        sequence: !input action_1_short_release
      - conditions:
          - condition: template
            value_template: "{{ action == '2_initial_press' }}"
        sequence: !input action_2_initial_press
      - conditions:
          - condition: template
            value_template: "{{ action == '1_long_release' }}"
        sequence: !input action_1_long_release
      - conditions:
          - condition: template
            value_template: "{{ action == '1_double_press' }}"
        sequence: !input action_1_double_press
      - conditions:
          - condition: template
            value_template: "{{ action == '1_long_press' }}"
        sequence:
          - repeat:
              sequence: !input action_1_long_press
              while:
                - condition: template
                  value_template: "{{ true }}"
      - conditions:
          - condition: template
            value_template: "{{ action == '2_short_release' }}"
        sequence: !input action_2_short_release
      - conditions:
          - condition: template
            value_template: "{{ action == '2_double_press' }}"
        sequence: !input action_2_double_press
      - conditions:
          - condition: template
            value_template: "{{ action == '2_long_release' }}"
        sequence: !input action_2_long_release
      - conditions:
          - condition: template
            value_template: "{{ action == '2_long_press' }}"
        sequence:
          - repeat:
              sequence: !input action_2_long_press
              while:
                - condition: template
                  value_template: "{{ true }}"
