blueprint:
  name: Motion triggered rgb light with user change
  description: Turn a light on based on detected motion and current brightness turn on or off only when user hasn't changed the light
  source_url: https://github.com/lucalouwris/automations/blob/main/MotionRGB.yaml
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: This sensor will be synchronized with the light.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    target_light:
      name: Lights
      description: The lights to keep in sync.
      selector:
        target:
          entity:
            domain: light
    target_brightness:
      name: Brightness for the light
      description: How bright the light should be when triggered
      default: 200
      selector:
        number:
          min: 1.0
          max: 255.0
          unit_of_measurement: ''
          step: 1.0
          mode: slider
    lux_sensor:
      name: Lux Sensor
      description: The brightness sensor to compare to.
      selector:
        target:
          entity:
            domain: sensor
    max_lux:
      name: Max lux value
      description: The maximum brightness for when to still trigger the light.
      default: 400
      selector:
        number:
          min: 0.0
          max: 3600.0
          unit_of_measurement: lux
          step: 1.0
          mode: slider

alias: Motion triggered light w. overwrite
description: "Light triggers based on motion sensor except when it's alreay on or light changed brightness compared to motion light"
trigger:
  - platform: state
    entity_id: !input motion_sensor
condition: []
action:
  - variables:
      AutoBrightness: !input target_brightness
      AutoLight: !input target_light
  - if:
      - condition: state
        entity_id: !input motion_sensor
        state: "on"
      - condition: state
        entity_id: !input target_light
        state: "off"
      - condition: numeric_state
        entity_id: !input lux_sensor
        below: !input max_lux
    then:
      - service: light.turn_on
        data:
          brightness: !input target_brightness
        target:
          entity_id: !input target_light
  - if:
      - condition: state
        entity_id: !input motion_sensor
        state: "off"
      - condition: template
        value_template: "{{ (state_attr(AutoLight, 'brightness')|int) == AutoBrightness - 1 }}"
    then:
      - service: light.turn_off
        data: {}
        target:
          entity_id: !input target_light
mode: single
