blueprint:
  name: "Motion light with lux sensor"
  description: "Light triggers based on motion sensor when a number is below a defined variable for example a lux sensor"
  source_url: https://github.com/lucalouwris/automations/blob/main/MotionLightLux.yaml
  domain: automation
  input:
    motion_sensor:
      name: "Motion Sensor"
      description: "This sensor or sensor group will be used to trigger the automation."
      selector:
        entity:
          domain: binary_sensor
    target_light:
      name: "Light"
      description: "The light or light group to trigger."
      selector:
        entity:
          domain: light
    lux_sensor:
      name: "Lux Sensor"
      description: "The lux sensor to grab the lux value."
      selector:
        entity:
          domain: sensor
    max_lux:
      name: "Max lux value"
      description: "The maximum lux for when to still trigger the light."
      default: 400
      selector:
        number:
          min: 0.0
          max: 3600.0
          unit_of_measurement: lux
          step: 1.0
          mode: slider

alias: "Motion triggered light w. lux sensor"
description: "Light triggers based on motion sensor when a number is below a defined variable"
trigger:
  - platform: state
    entity_id: !input motion_sensor
condition: []
action:
  - if:
      - condition: state
        entity_id: !input motion_sensor
        state: "on"
      - condition: numeric_state
        entity_id: !input lux_sensor
        below: !input max_lux
    then:
      - service: light.turn_on
        target:
          entity_id: !input target_light
  - if:
      - condition: state
        entity_id: !input motion_sensor
        state: "off"
    then:
      - service: light.turn_off
        data: {}
        target:
          entity_id: !input target_light
mode: single
