blueprint:
  name: Motion Light With lux sensor
  description: Turn a light on based on detected motion and current brightness
  source_url: https://github.com/lucalouwris/automations/blob/main/motion_lux_light.yaml
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: This sensor will be synchronized with the light.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    target_light:
      name: Lights
      description: The lights to keep in sync.
      selector:
        target:
          entity:
            domain: light
    brightness_sensor:
      name: Brightness Sensor
      description: The brightness sensor to compare to.
      selector:
        target:
          entity:
            domain: sensor
    below_brightness:
      name: Brightness value
      description: The maximum brightness for when to still trigger the light.
      default: 400
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: lux
    no_motion_wait:
          name: Wait time
          description: Time to leave the light on after last motion is detected.
          default: 10
          selector:
            number:
              min: 0
              max: 3600
              unit_of_measurement: seconds

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"

condition:
  - condition: numeric_state
    entity_id: !input brightness_sensor
    below: !input below_brightness

action:
  - service: light.turn_on
    target: !input target_light
  - wait_for_trigger:
      platform: state
      entity_id: !input motion_sensor
      from: "on"
      to: "off"
  - delay: !input no_motion_wait
  - service: light.turn_off
    target: !input target_light
