blueprint:
  name: Motion triggered rgb light with user change
  description: Turn a light on based on detected motion and current brightness turn on or off only when user hasn't changed the light
  source_url: https://github.com/lucalouwris/automations/blob/main/MotionLightLux.yaml
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: This sensor will be synchronized with the light.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    target_light:
      name: Lights
      description: The lights to keep in sync.
      selector:
        entity:
          domain: light
    lux_sensor:
      name: Lux Sensor
      description: The brightness sensor to compare to.
      selector:
        entity:
          domain: sensor
    max_lux:
      name: Max lux value
      description: The maximum brightness for when to still trigger the light.
      default: 400
      selector:
        number:
          min: 0.0
          max: 3600.0
          unit_of_measurement: lux
          step: 1.0
          mode: slider

alias: Motion triggered light w. overwrite
description: "Light triggers based on motion sensor except when it's alreay on or light changed brightness compared to motion light"
trigger:
  - platform: state
    entity_id: !input motion_sensor
condition: []
action:
  - if:
      - condition: state
        entity_id: !input motion_sensor
        state: "on"
      - condition: numeric_state
        entity_id: !input lux_sensor
        below: !input max_lux
    then:
      - service: light.turn_on
        target:
          entity_id: !input target_light
  - if:
      - condition: state
        entity_id: !input motion_sensor
        state: "off"
    then:
      - service: light.turn_off
        data: {}
        target:
          entity_id: !input target_light
mode: single
